/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ComboModeloEmitente;
import controller.EtiquetaController;
import dao.EmitenteDAO;
import dao.EtiquetaDAO;
import dao.EtiquetaPropriedadeDAO;
import dao.LayoutDAO;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.sql.Array;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.Emitente;
import model.Etiqueta;
import model.Layout;

/**
 *
 * @author Administrador
 */
public class TelaImprimeEtiquetaCaixa extends javax.swing.JDialog {

    DefaultTableModel modeloTable;

    Layout layout;
    List<Etiqueta> etiquetasIndividuais;
    Etiqueta etiquetaIndividual = null;

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    boolean novo = true;
    Emitente emitente = null;
    java.awt.Frame parent;
    ArrayList<Layout> layouts = new ArrayList<Layout>();

    /**
     * Creates new form ManutencaoUsuario
     */
    public TelaImprimeEtiquetaCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        populaComboEmitente();

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(3);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    private void populaComboEmitente() {
        comboEmitente.removeAllItems();

        EmitenteDAO emitenteDAO = new EmitenteDAO();
        ArrayList<Emitente> emitentes = (ArrayList<Emitente>) emitenteDAO.selectAll();
        comboEmitente.setModel(new ComboModeloEmitente(emitentes));

        if (emitentes.size() > 0) {
            comboEmitente.setSelectedItem(emitentes.get(0));
            emitente = emitentes.get(0);
            populaComboLayout();
        }

    }

    private void populaComboLayout() {
        try {
            if (comboLayout.getItemCount() > 0) {
                comboLayout.removeAllItems();
            }
            if (emitente != null) {
                LayoutDAO layoutDAO = new LayoutDAO();
                layouts = (ArrayList<Layout>) layoutDAO.selectAllEmitente(emitente.getId());

                layouts.forEach((layout) -> {
                    if (layout.getTipo() == 1) {
                        comboLayout.addItem(layout.getCodigo());
                    }
                });

                if (comboLayout.getItemCount() > 0) {                    
                    comboLayout.setSelectedIndex(0);
                    layoutDAO = new LayoutDAO();
                    System.out.println("Layout selecionado: " + comboLayout.getSelectedItem().toString());
                    layout = layoutDAO.selectWhereCodigo(emitente.getId(), comboLayout.getSelectedItem().toString());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonImprimir = new javax.swing.JButton();
        comboEmitente = new javax.swing.JComboBox<>();
        comboLayout = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonCarregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textEtiqueta = new javax.swing.JTextField();
        textLidas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Gestão77 - Impressão de Etiquetas de Caixa");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cancelButton.setLabel("Fechar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Etiquetas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonImprimir.setText("Imprimir Etiqueta Embalagem");
        buttonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirActionPerformed(evt);
            }
        });

        comboEmitente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEmitente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEmitenteItemStateChanged(evt);
            }
        });

        comboLayout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLayout.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLayoutItemStateChanged(evt);
            }
        });

        jLabel1.setText("Cliente:");

        jLabel2.setText("Layout:");

        buttonCarregar.setText("OK");
        buttonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarregarActionPerformed(evt);
            }
        });

        jLabel3.setText("Etiqueta:");

        textEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEtiquetaActionPerformed(evt);
            }
        });
        textEtiqueta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textEtiquetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textEtiquetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEtiquetaKeyTyped(evt);
            }
        });

        textLidas.setEditable(false);

        jLabel4.setText("Lidas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboLayout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboEmitente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textEtiqueta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textLidas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCarregar)
                    .addComponent(jLabel3)
                    .addComponent(textEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonImprimir)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void buttonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirActionPerformed
        // TODO add your handling code here:
        //retorna um inteiro
        imprimeEtiquetaCaixa();
    }//GEN-LAST:event_buttonImprimirActionPerformed

    private void comboEmitenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEmitenteItemStateChanged
        // TODO add your handling code here:
        try {
            emitente = (Emitente) comboEmitente.getSelectedItem();
            populaComboLayout();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_comboEmitenteItemStateChanged

    private void buttonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarregarActionPerformed
        // TODO add your handling code here:
        if (valida()) {
            populaTabela();
        }
        textEtiqueta.setText("");
    }//GEN-LAST:event_buttonCarregarActionPerformed

    private void comboLayoutItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLayoutItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_comboLayoutItemStateChanged

    private void textEtiquetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEtiquetaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textEtiquetaKeyPressed

    private void textEtiquetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEtiquetaKeyReleased
        // TODO add your handling code here:
        if(textEtiqueta.getText().length() == layout.getComprimentoChave()){
            if (valida()) {
                populaTabela();
            }
            textEtiqueta.setText("");
        }        
    }//GEN-LAST:event_textEtiquetaKeyReleased

    private void textEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEtiquetaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textEtiquetaActionPerformed

    private void textEtiquetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEtiquetaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textEtiquetaKeyTyped

    public boolean valida() {
        
        if (layout == null) {
            LayoutDAO layoutDAO = new LayoutDAO();
            System.out.println("Layout selecionado: " + comboLayout.getSelectedItem().toString());
            layout = layoutDAO.selectWhereCodigo(emitente.getId(), comboLayout.getSelectedItem().toString());
        }
        
        if(textEtiqueta.getText().length() != layout.getComprimentoChave()){
            JOptionPane.showMessageDialog(this, "Código de barras não tem o comprimento informado no layout", "Código de Barras Inválido", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(jTable1.getRowCount() == 0 || etiquetasIndividuais == null)
            etiquetasIndividuais = new ArrayList<Etiqueta>();
        
        EtiquetaDAO etiquetaDAO = new EtiquetaDAO();
        
        System.out.println("Emitente Imp: " + emitente.getId());
        
        etiquetaIndividual = etiquetaDAO.selectWhereEmitenteChave(emitente.getId(), textEtiqueta.getText());
        
        System.out.println("A");
        
        if (etiquetaIndividual == null) {
            JOptionPane.showMessageDialog(this, "Etiqueta inexistente", "Etiqueta inexistente", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        System.out.println("B");

        if (etiquetaIndividual.getSituacao() == 3) {
            JOptionPane.showMessageDialog(this, "Etiqueta já embalada", "Etiqueta Embalada", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        System.out.println("C: " + etiquetaIndividual.getSituacao() + " - " + etiquetaIndividual.getChaveUnica());

        //etiqueta não foi impressa mas layout caixa válida impressao
        if (etiquetaIndividual.getSituacao() == 1 /*Não Impressa*/ && layout.isValidaImpressaoCaixa()) {
            JOptionPane.showMessageDialog(this, "Etiqueta não está impressa", "Imprimir Etiqueta", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        System.out.println("D");
        
        for(Etiqueta etiq : etiquetasIndividuais){
            if(etiquetaIndividual.getChaveUnica().equals(etiq.getChaveUnica())){
                JOptionPane.showMessageDialog(this, "Etiqueta já lida nesta embalagem", "Etiqueta Lida", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        System.out.println("E");
        
        return true;
    }

    public void imprimeEtiquetaCaixa() {
        //Abertura da impressora  
        EtiquetaController etiquetaController = new EtiquetaController();
        List<Etiqueta> etiquetas = new ArrayList<Etiqueta>();
        
        int[] linhasMarcadas = jTable1.getSelectedRows();

        List<Etiqueta> etiquetasImp = new ArrayList<Etiqueta>();
        EtiquetaDAO etiquetaDAO = new EtiquetaDAO();
        for (int i = 0; i < linhasMarcadas.length; i++) {
            System.out.println("ID Etiq " + jTable1.getModel().getValueAt(linhasMarcadas[i], 0));
            int idEtiq = (int) jTable1.getModel().getValueAt(linhasMarcadas[i], 0);
            etiquetas.add(etiquetaDAO.select(idEtiq));
        }

        for (Etiqueta etiqAux : etiquetas) {
            System.out.println("Imprimir " + etiqAux.getConteudo());
        }

        etiquetaController.imprimeEtiquetaEmbalagem(etiquetasImp, layout);

        JOptionPane.showMessageDialog(this, "As etiquetas marcadas foram impressas...", "Etiquetas Impressas", JOptionPane.INFORMATION_MESSAGE);

        populaTabela();

    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public void setEmitente(Emitente emitente) {
        this.emitente = emitente;
        populaTabela();
    }

    private void populaTabela() {
        
        modeloTable = (DefaultTableModel) jTable1.getModel();
        
        etiquetasIndividuais.add(etiquetaIndividual);
        
        modeloTable.addRow(new Object[]{
            etiquetaIndividual.getChaveUnica()});

        textLidas.setText(Integer.toString(jTable1.getRowCount()));

        if (jTable1.getRowCount() >= layout.getQuantidadeCaixa()) {
            EtiquetaController etiquetaController = new EtiquetaController();
            etiquetaController.imprimeEtiquetaEmbalagem(etiquetasIndividuais, layout);
            limpaTabela();
        }

    }

    private void limpaTabela() {

        modeloTable = (DefaultTableModel) jTable1.getModel();

        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        
        textLidas.setText(Integer.toString(jTable1.getRowCount()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImprimeEtiquetaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImprimeEtiquetaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImprimeEtiquetaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImprimeEtiquetaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaImprimeEtiquetaCaixa dialog = new TelaImprimeEtiquetaCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCarregar;
    private javax.swing.JButton buttonImprimir;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> comboEmitente;
    private javax.swing.JComboBox<String> comboLayout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textEtiqueta;
    private javax.swing.JTextField textLidas;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
