/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.LayoutDAO;
import dao.EmitenteDAO;
import dao.LayoutPropriedadeDAO;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.Layout;
import model.Emitente;
import model.LayoutPropriedade;

/**
 *
 * @author Administrador
 */
public class TelaEditaLayout extends javax.swing.JDialog {
    
    List<LayoutPropriedade> propriedades = new ArrayList<LayoutPropriedade>();

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    boolean novo = true;
    Layout layout;
    Emitente emitente;
    
    String fonteLayoutAux = null;
    
    private int returnStatus = RET_CANCEL;
    
    Frame pai;
    
    /**
     * Creates new form ManutencaoUsuario
     */
    public TelaEditaLayout(Frame parent, boolean modal) {
        super(parent, modal);
        pai = parent;
        initComponents();
        URL url = this.getClass().getResource("/image/logoVerticalClean.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(3);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(3);
        habilitaCampoCaixa();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectValidaImpressao = new javax.swing.JCheckBox();
        textRazao = new javax.swing.JTextField();
        textCodigo = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        textQuantidadeCaixa = new javax.swing.JTextField();
        buttonFonte = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        buttonEditaProp = new javax.swing.JButton();
        textImpressora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textPulaEtiqueta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textComprimentoChave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Gestão77 - Edição de Layouts");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        jLabel2.setText("Código:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Quantidade Caixa:");

        selectValidaImpressao.setSelected(true);
        selectValidaImpressao.setText("Valida Impressão da Etiqueta Individual");
        selectValidaImpressao.setName(""); // NOI18N

        textRazao.setEditable(false);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Caixa", "Avulsa" }));
        comboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoItemStateChanged(evt);
            }
        });
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        buttonFonte.setText("Editar Fonte");
        buttonFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFonteActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hashtag", "Obtencão", "Único"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Propriedades:");

        buttonEditaProp.setText("Editar Propriedade");
        buttonEditaProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditaPropActionPerformed(evt);
            }
        });

        jLabel6.setText("Impressora:");

        jLabel7.setText("Pula Etiqueta:");

        jLabel8.setText("Comp. Codigo Barra:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textRazao)
                    .addComponent(textCodigo)
                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(buttonEditaProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textImpressora)
                    .addComponent(textQuantidadeCaixa)
                    .addComponent(textComprimentoChave)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectValidaImpressao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textPulaEtiqueta)
                    .addComponent(buttonFonte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(textQuantidadeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textComprimentoChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPulaEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectValidaImpressao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFonte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditaProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(cancelButton))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
                          
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged
        // TODO add your handling code here:
        habilitaCampoCaixa();
    }//GEN-LAST:event_comboTipoItemStateChanged

    private void buttonFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFonteActionPerformed
        // TODO add your handling code here:
        TelaEditaFonteLayout telaEditaFonteLayout = new TelaEditaFonteLayout(pai, true);
        /*if(layout != null)
            telaEditaFonteLayout.setFonteLayout(layout.getFonteLayout());
        else*/
            telaEditaFonteLayout.setFonteLayout(fonteLayoutAux);
        
        telaEditaFonteLayout.show();

        if(telaEditaFonteLayout.getReturnStatus()==1){
            fonteLayoutAux = telaEditaFonteLayout.getReturnFont();
            
            //fazer tratamento dos campos variaveis da etiqueta
            int comprimento = fonteLayoutAux.length();
            int posHash = -1;
            
            List<LayoutPropriedade> propriedadesAux = new ArrayList<LayoutPropriedade>();
            
            System.out.println("Comprimento: " + comprimento);
            for (int i=0; i < comprimento; i++) {
                if(fonteLayoutAux.charAt(i) == '#')
                    posHash = i;
                
                if((fonteLayoutAux.charAt(i) == '^' || fonteLayoutAux.charAt(i) == ',') && posHash != -1){
                    String propAux = fonteLayoutAux.substring(posHash, i);
                    System.out.println("Propriedade: " + propAux);
                    posHash = -1;
                    propriedadesAux.add(new LayoutPropriedade(propAux));
                }
                
            }
            
            int achou = 0;
            for(int i = 0; i < propriedades.size(); i++){
                achou = 0;
                for(int x = 0; x < propriedadesAux.size(); x++){
                    if(propriedades.get(i).getPropriedade().equals(propriedadesAux.get(x).getPropriedade())){
                        achou = 1;
                        x = propriedadesAux.size();
                    }
                }
                if(achou == 0){
                    propriedades.remove(i);
                }
                
            }
            
            for(int i = 0; i < propriedadesAux.size(); i++){
                achou = 0;
                for(int x = 0; x < propriedades.size(); x++){
                    if(propriedades.get(x).getPropriedade().equals(propriedadesAux.get(i).getPropriedade())){
                        achou = 1;
                        x = propriedades.size();
                    }
                }
                if(achou == 0){
                    System.out.println("Adicionando: " + propriedadesAux.get(i).getPropriedade());
                    propriedades.add(propriedadesAux.get(i));
                }
            }
            
            for(int i = 0; i < propriedades.size(); i++){
                if(propriedades.get(i).getOrigem() == 0){
                    System.out.println("Valida Origem");
                    propriedades.get(i).setOrigem(propriedades.get(i).validaOrigem());
                }
            }
            //populaPropriedades();
            populaPropriedadesTela();
            
        }
    }//GEN-LAST:event_buttonFonteActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if(validar() == true){
            salvar();
            doClose(RET_OK);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void buttonEditaPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditaPropActionPerformed
        // TODO add your handling code here:
        LayoutPropriedade propriedade = propriedades.get((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
        if(propriedade.getOrigem() == 3){
            JOptionPane.showMessageDialog(this, "Esta propriedade tem como origem uma tabela, não pode ser alterada.", "Propriedade não pode ser editada", JOptionPane.ERROR_MESSAGE);
        }else{
            TelaEditaLayoutPropriedade telaEditaLayoutPropriedade = new TelaEditaLayoutPropriedade(pai, true);
            telaEditaLayoutPropriedade.setLayoutPropriedade(propriedade);
            telaEditaLayoutPropriedade.setIdLayout(propriedade.getIdLayout());
            telaEditaLayoutPropriedade.show();
            propriedade = telaEditaLayoutPropriedade.getLayoutPropriedade();
            jTable1.setValueAt(propriedade.retornaOrigemString(), jTable1.getSelectedRow(), 2);
            jTable1.setValueAt(propriedade.retornaChaveUnica(), jTable1.getSelectedRow(), 3);
        }
        
        /*String propriedade = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString(); 
        System.out.println("Propriedade selecionada " + propriedade);
        LayoutPropriedadeDAO layoutPropriedadeDAO = new LayoutPropriedadeDAO();
        LayoutPropriedade layoutPropriedadeAux = layoutPropriedadeDAO.selectWherePropriedade(ABORT, propriedade)
        Emitente emitente = emitenteDAO.selectWhereCnpj(cnpj);
        System.out.println("Emitente encontrado " + emitente.getRazao());*/
    }//GEN-LAST:event_buttonEditaPropActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    public void setLayout(Layout layout, Emitente emitente){
        this.emitente = emitente;
        textRazao.setText(emitente.getRazao());
        if(layout != null){
            System.out.println("SETANDO LAYOUT");
            this.layout = layout;
            textCodigo.setText(layout.getCodigo());
            textCodigo.setEnabled(false);
            comboTipo.setSelectedIndex(layout.getTipo());
            comboTipo.setEnabled(false);
            textQuantidadeCaixa.setText(Integer.toString(layout.getQuantidadeCaixa()));
            textPulaEtiqueta.setText(Integer.toString(layout.getPulaEtiqueta()));
            textImpressora.setText(layout.getImpressora());
            selectValidaImpressao.setSelected(layout.isValidaImpressaoCaixa());
            textComprimentoChave.setText(Integer.toString(layout.getComprimentoChave()));
            comboTipo.requestFocus();
            fonteLayoutAux = layout.getFonteLayout();
            populaPropriedades();
            populaPropriedadesTela();
            novo = false;
        }else{
            textCodigo.requestFocus();
            fonteLayoutAux = "";
            novo = true;
        }
        
    }
    
    public Layout getObjetoLayout(){
        return layout;
    }
    
    private void salvar(){
        LayoutDAO layoutDAO = new LayoutDAO();
        if(novo == true){
            System.out.println("NOVO LAYOUT");
            layout = new Layout(emitente.getId(), textCodigo.getText(), comboTipo.getSelectedIndex(), Integer.parseInt(textQuantidadeCaixa.getText()), selectValidaImpressao.isSelected(), fonteLayoutAux, Integer.parseInt(textComprimentoChave.getText()));
            layoutDAO.insert(layout);
            //layout = layoutDAO.selectWhereCodigo(emitente.getId(), textCodigo.getText());
        }else{
            layout.setIdEmitente(emitente.getId());
            layout.setCodigo(textCodigo.getText());
            layout.setTipo(comboTipo.getSelectedIndex());
            layout.setQuantidadeCaixa(Integer.parseInt(textQuantidadeCaixa.getText()));
            layout.setValidaImpressaoCaixa(selectValidaImpressao.isSelected());
            layout.setFonteLayout(fonteLayoutAux);
            layout.setPulaEtiqueta(Integer.parseInt(textPulaEtiqueta.getText()));
            layout.setComprimentoChave(Integer.parseInt(textComprimentoChave.getText()));
            layout.setImpressora(textImpressora.getText());
            layoutDAO.update(layout);            
        }
        LayoutPropriedadeDAO layoutPropriedadeDAO = new LayoutPropriedadeDAO();
        layoutPropriedadeDAO.deleteLote(layout.getId());
        for(int i = 0; i < propriedades.size(); i++){
            propriedades.get(i).setIdLayout(layout.getId());
            propriedades.get(i).setId(0);            
        }
        layoutPropriedadeDAO.insertLote(propriedades);        
    }
    
    private void populaPropriedadesTela(){
        
        DefaultTableModel modeloTable = (DefaultTableModel) jTable1.getModel();
        
        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        
        if(propriedades != null){
            for(int i = 0; i < propriedades.size(); i++){
                modeloTable.addRow(new Object[] {
                    i,
                    propriedades.get(i).getPropriedade(),
                    propriedades.get(i).retornaOrigemString(),
                    propriedades.get(i).retornaChaveUnica()});
            }
        }
    }
    
    private void populaPropriedades(){
       LayoutPropriedadeDAO layoutPropriedadeDAO = new LayoutPropriedadeDAO();
       propriedades = layoutPropriedadeDAO.selectAllLayoutPropriedades(layout.getId());        
    }
    
    private boolean validar(){
        //Verifica se não existe outro usuario com o mesmo login
        if(novo){
            LayoutDAO layoutDAO = new LayoutDAO();
            Layout layoutAux = layoutDAO.selectWhereCodigo(emitente.getId(), textCodigo.getText());
            if(layoutAux != null){
                JOptionPane.showMessageDialog(rootPane, "Layout já cadastrado com código informado para este emitente","Layout já cadastrado", JOptionPane.ERROR_MESSAGE);
                textCodigo.requestFocus();
                return false;                
            }
        }
        
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEditaLayout dialog = new TelaEditaLayout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void habilitaCampoCaixa(){
        if(comboTipo.getSelectedIndex() == 0 || comboTipo.getSelectedIndex() == 2){
            textQuantidadeCaixa.setEnabled(false);
            textQuantidadeCaixa.setText("0");
            textComprimentoChave.setEnabled(false);
            textComprimentoChave.setText("0");
            textPulaEtiqueta.setEnabled(true);
            textPulaEtiqueta.setText("0");
            selectValidaImpressao.setEnabled(false);
            selectValidaImpressao.setSelected(false);            
        }else{
            textQuantidadeCaixa.setEnabled(true);
            textQuantidadeCaixa.setText("0");
            textComprimentoChave.setEnabled(true);
            textComprimentoChave.setText("0");
            textPulaEtiqueta.setEnabled(false);
            textPulaEtiqueta.setText("0");
            selectValidaImpressao.setEnabled(true);
            selectValidaImpressao.setSelected(false);             
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditaProp;
    private javax.swing.JButton buttonFonte;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox selectValidaImpressao;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textComprimentoChave;
    private javax.swing.JTextField textImpressora;
    private javax.swing.JTextField textPulaEtiqueta;
    private javax.swing.JTextField textQuantidadeCaixa;
    private javax.swing.JTextField textRazao;
    // End of variables declaration//GEN-END:variables
}
